// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarss = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

const sidebars = {
  docsSidebar: [
    // ─────────────────────────────────────────────
    // OVERVIEW
    // ─────────────────────────────────────────────
    'intro',
    'how-solydflow-works',

    // ─────────────────────────────────────────────
    // GET STARTED
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: [
        'get-started/quickstart',
        'get-started/create-project',
        'get-started/install-sdk',
        'get-started/configure-solydflow',
        'get-started/first-purchase',
      ],
    },

    // ─────────────────────────────────────────────
    // CONCEPTS
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/projects',
        'concepts/users',
        'concepts/products',
        'concepts/packages',
        'concepts/pricing',
        'concepts/paywalls',
        'concepts/entitlements',
        'concepts/transactions',
        'concepts/transaction-states',
      ],
    },

    // ─────────────────────────────────────────────
    // MONETIZATION
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Monetization',
      collapsed: false,
      items: [
        'monetization/overview',
        'monetization/products-and-packages',
        'monetization/regional-pricing',
        'monetization/discounts',
        'monetization/changing-pricing',
      ],
    },

    // ─────────────────────────────────────────────
    // PAYMENT PROVIDERS
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Payment Providers',
      collapsed: true,
      items: [
        'payment-providers/overview',
        'payment-providers/stripe',
        'payment-providers/paystack',
        'payment-providers/flutterwave',
        'payment-providers/mpesa',
        'payment-providers/monnify',
        'payment-providers/apple',
        'payment-providers/google-play',
      ],
    },

    // ─────────────────────────────────────────────
    // RECOVER
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Recover',
      collapsed: true,
      items: [
        'recover/overview',
        'recover/transaction-recovery',
        'recover/zombie-transactions',
        'recover/failed-webhooks',
        'recover/retries',
        'recover/recovery-workflows',
      ],
    },

    // ─────────────────────────────────────────────
    // TRUTH
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Truth',
      collapsed: true,
      items: [
        'truth/overview',
        'truth/transaction-verification',
        'truth/consensus-engine',
        'truth/transaction-ledger',
        'truth/state-mismatches',
        'truth/reconciliation',
      ],
    },

    // ─────────────────────────────────────────────
    // ENFORCE
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Enforce',
      collapsed: true,
      items: [
        'enforce/overview',
        'enforce/smart-routing',
        'enforce/provider-failover',
        'enforce/transaction-finality',
        'enforce/entitlement-enforcement',
      ],
    },

    // ─────────────────────────────────────────────
    // WEBHOOKS
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Webhooks',
      collapsed: true,
      items: [
        'webhooks/overview',
        'webhooks/inbound-webhooks',
        'webhooks/provider-webhooks',
        'webhooks/signature-verification',
        'webhooks/event-handling',
      ],
    },

    // ─────────────────────────────────────────────
    // SDK
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'SDK',
      collapsed: true,
      items: [
        'sdk/overview',
        'sdk/javascript',
        'sdk/flutter',
        'sdk/react-native',
        'sdk/swift',
        'sdk/kotlin',
        'sdk/other-languages',
      ],
    },

    // ─────────────────────────────────────────────
    // SANDBOX
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Sandbox',
      collapsed: true,
      items: [
        'sandbox/overview',
        'sandbox/test-transactions',
        'sandbox/simulate-failures',
        'sandbox/testing-recovery',
      ],
    },

    // ─────────────────────────────────────────────
    // SECURITY
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [
        'security/overview',
        'security/api-keys',
        'security/credential-security',
        'security/webhook-security',
        'security/encryption',
        'security/audit-logs',
        'security/compliance',
      ],
    },

    // ─────────────────────────────────────────────
    // GLOBAL COMMERCE
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Global Commerce',
      collapsed: true,
      items: [
        'global-commerce/overview',
        'global-commerce/local-payments',
        'global-commerce/international-payments',
        'global-commerce/merchant-of-record',
        'global-commerce/tax-and-compliance',
        'global-commerce/multi-currency',
      ],
    },

    // ─────────────────────────────────────────────
    // GUIDES
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/saas',
        'guides/mobile-apps',
        'guides/web-apps',
        'guides/edtech',
        'guides/marketplaces',
        'guides/multi-country-commerce',
      ],
    },

    // ─────────────────────────────────────────────
    // TROUBLESHOOTING
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      items: [
        'troubleshooting/overview',
        'troubleshooting/payment-pending',
        'troubleshooting/webhook-not-received',
        'troubleshooting/entitlement-not-granted',
        'troubleshooting/transaction-state-mismatch',
        'troubleshooting/provider-errors',
      ],
    },

    // ─────────────────────────────────────────────
    // PRODUCTION
    // ─────────────────────────────────────────────
    {
      type: 'category',
      label: 'Production',
      collapsed: true,
      items: [
        'production/production-checklist',
        'production/going-live',
        'production/monitoring',
      ],
    },
  ],
};


export default sidebars;
